;;; eaw.el --- Fix east asian ambiguous width issue for emacs
;; Author: HAMANO Tsukasa <code@cuspy.org>
;; URL: https://github.com/hamano/locale-eaw
;; Version: 12
;; MIT License

;;; Code:

(setq east-asian-ambiguous '(
  #x00A1 ; Po         INVERTED EXCLAMATION MARK
  #x00A4 ; Sc         CURRENCY SIGN
  #x00A7 ; Po         SECTION SIGN
  #x00A8 ; Sk         DIAERESIS
  #x00AA ; Lo         FEMININE ORDINAL INDICATOR
  #x00AD ; Cf         SOFT HYPHEN
  #x00AE ; So         REGISTERED SIGN
  #x00B0 ; So         DEGREE SIGN
  #x00B1 ; Sm         PLUS-MINUS SIGN
  #x00B2 ; No     [2] SUPERSCRIPT TWO..SUPERSCRIPT THREE
  #x00B3 ; No     [2] SUPERSCRIPT TWO..SUPERSCRIPT THREE
  #x00B4 ; Sk         ACUTE ACCENT
  #x00B6 ; Po     [2] PILCROW SIGN..MIDDLE DOT
  #x00B7 ; Po     [2] PILCROW SIGN..MIDDLE DOT
  #x00B8 ; Sk         CEDILLA
  #x00B9 ; No         SUPERSCRIPT ONE
  #x00BA ; Lo         MASCULINE ORDINAL INDICATOR
  #x00BC ; No     [3] VULGAR FRACTION ONE QUARTER..VULGAR FRACTION THREE QUARTERS
  #x00BD ; No     [3] VULGAR FRACTION ONE QUARTER..VULGAR FRACTION THREE QUARTERS
  #x00BE ; No     [3] VULGAR FRACTION ONE QUARTER..VULGAR FRACTION THREE QUARTERS
  #x00BF ; Po         INVERTED QUESTION MARK
  #x00C6 ; Lu         LATIN CAPITAL LETTER AE
  #x00D0 ; Lu         LATIN CAPITAL LETTER ETH
  #x00D7 ; Sm         MULTIPLICATION SIGN
  #x00D8 ; Lu         LATIN CAPITAL LETTER O WITH STROKE
  #x00DE ; L&     [4] LATIN CAPITAL LETTER THORN..LATIN SMALL LETTER A WITH ACUTE
  #x00DF ; L&     [4] LATIN CAPITAL LETTER THORN..LATIN SMALL LETTER A WITH ACUTE
  #x00E0 ; L&     [4] LATIN CAPITAL LETTER THORN..LATIN SMALL LETTER A WITH ACUTE
  #x00E1 ; L&     [4] LATIN CAPITAL LETTER THORN..LATIN SMALL LETTER A WITH ACUTE
  #x00E6 ; Ll         LATIN SMALL LETTER AE
  #x00E8 ; Ll     [3] LATIN SMALL LETTER E WITH GRAVE..LATIN SMALL LETTER E WITH CIRCUMFLEX
  #x00E9 ; Ll     [3] LATIN SMALL LETTER E WITH GRAVE..LATIN SMALL LETTER E WITH CIRCUMFLEX
  #x00EA ; Ll     [3] LATIN SMALL LETTER E WITH GRAVE..LATIN SMALL LETTER E WITH CIRCUMFLEX
  #x00EC ; Ll     [2] LATIN SMALL LETTER I WITH GRAVE..LATIN SMALL LETTER I WITH ACUTE
  #x00ED ; Ll     [2] LATIN SMALL LETTER I WITH GRAVE..LATIN SMALL LETTER I WITH ACUTE
  #x00F0 ; Ll         LATIN SMALL LETTER ETH
  #x00F2 ; Ll     [2] LATIN SMALL LETTER O WITH GRAVE..LATIN SMALL LETTER O WITH ACUTE
  #x00F3 ; Ll     [2] LATIN SMALL LETTER O WITH GRAVE..LATIN SMALL LETTER O WITH ACUTE
  #x00F7 ; Sm         DIVISION SIGN
  #x00F8 ; Ll     [3] LATIN SMALL LETTER O WITH STROKE..LATIN SMALL LETTER U WITH ACUTE
  #x00F9 ; Ll     [3] LATIN SMALL LETTER O WITH STROKE..LATIN SMALL LETTER U WITH ACUTE
  #x00FA ; Ll     [3] LATIN SMALL LETTER O WITH STROKE..LATIN SMALL LETTER U WITH ACUTE
  #x00FC ; Ll         LATIN SMALL LETTER U WITH DIAERESIS
  #x00FE ; Ll         LATIN SMALL LETTER THORN
  #x0101 ; Ll         LATIN SMALL LETTER A WITH MACRON
  #x0111 ; Ll         LATIN SMALL LETTER D WITH STROKE
  #x0113 ; Ll         LATIN SMALL LETTER E WITH MACRON
  #x011B ; Ll         LATIN SMALL LETTER E WITH CARON
  #x0126 ; L&     [2] LATIN CAPITAL LETTER H WITH STROKE..LATIN SMALL LETTER H WITH STROKE
  #x0127 ; L&     [2] LATIN CAPITAL LETTER H WITH STROKE..LATIN SMALL LETTER H WITH STROKE
  #x012B ; Ll         LATIN SMALL LETTER I WITH MACRON
  #x0131 ; L&     [3] LATIN SMALL LETTER DOTLESS I..LATIN SMALL LIGATURE IJ
  #x0132 ; L&     [3] LATIN SMALL LETTER DOTLESS I..LATIN SMALL LIGATURE IJ
  #x0133 ; L&     [3] LATIN SMALL LETTER DOTLESS I..LATIN SMALL LIGATURE IJ
  #x0138 ; Ll         LATIN SMALL LETTER KRA
  #x013F ; L&     [4] LATIN CAPITAL LETTER L WITH MIDDLE DOT..LATIN SMALL LETTER L WITH STROKE
  #x0140 ; L&     [4] LATIN CAPITAL LETTER L WITH MIDDLE DOT..LATIN SMALL LETTER L WITH STROKE
  #x0141 ; L&     [4] LATIN CAPITAL LETTER L WITH MIDDLE DOT..LATIN SMALL LETTER L WITH STROKE
  #x0142 ; L&     [4] LATIN CAPITAL LETTER L WITH MIDDLE DOT..LATIN SMALL LETTER L WITH STROKE
  #x0144 ; Ll         LATIN SMALL LETTER N WITH ACUTE
  #x0148 ; L&     [4] LATIN SMALL LETTER N WITH CARON..LATIN SMALL LETTER ENG
  #x0149 ; L&     [4] LATIN SMALL LETTER N WITH CARON..LATIN SMALL LETTER ENG
  #x014A ; L&     [4] LATIN SMALL LETTER N WITH CARON..LATIN SMALL LETTER ENG
  #x014B ; L&     [4] LATIN SMALL LETTER N WITH CARON..LATIN SMALL LETTER ENG
  #x014D ; Ll         LATIN SMALL LETTER O WITH MACRON
  #x0152 ; L&     [2] LATIN CAPITAL LIGATURE OE..LATIN SMALL LIGATURE OE
  #x0153 ; L&     [2] LATIN CAPITAL LIGATURE OE..LATIN SMALL LIGATURE OE
  #x0166 ; L&     [2] LATIN CAPITAL LETTER T WITH STROKE..LATIN SMALL LETTER T WITH STROKE
  #x0167 ; L&     [2] LATIN CAPITAL LETTER T WITH STROKE..LATIN SMALL LETTER T WITH STROKE
  #x016B ; Ll         LATIN SMALL LETTER U WITH MACRON
  #x01CE ; Ll         LATIN SMALL LETTER A WITH CARON
  #x01D0 ; Ll         LATIN SMALL LETTER I WITH CARON
  #x01D2 ; Ll         LATIN SMALL LETTER O WITH CARON
  #x01D4 ; Ll         LATIN SMALL LETTER U WITH CARON
  #x01D6 ; Ll         LATIN SMALL LETTER U WITH DIAERESIS AND MACRON
  #x01D8 ; Ll         LATIN SMALL LETTER U WITH DIAERESIS AND ACUTE
  #x01DA ; Ll         LATIN SMALL LETTER U WITH DIAERESIS AND CARON
  #x01DC ; Ll         LATIN SMALL LETTER U WITH DIAERESIS AND GRAVE
  #x0251 ; Ll         LATIN SMALL LETTER ALPHA
  #x0261 ; Ll         LATIN SMALL LETTER SCRIPT G
  #x02C4 ; Sk         MODIFIER LETTER UP ARROWHEAD
  #x02C7 ; Lm         CARON
  #x02C9 ; Lm     [3] MODIFIER LETTER MACRON..MODIFIER LETTER GRAVE ACCENT
  #x02CA ; Lm     [3] MODIFIER LETTER MACRON..MODIFIER LETTER GRAVE ACCENT
  #x02CB ; Lm     [3] MODIFIER LETTER MACRON..MODIFIER LETTER GRAVE ACCENT
  #x02CD ; Lm         MODIFIER LETTER LOW MACRON
  #x02D0 ; Lm         MODIFIER LETTER TRIANGULAR COLON
  #x02D8 ; Sk     [4] BREVE..OGONEK
  #x02D9 ; Sk     [4] BREVE..OGONEK
  #x02DA ; Sk     [4] BREVE..OGONEK
  #x02DB ; Sk     [4] BREVE..OGONEK
  #x02DD ; Sk         DOUBLE ACUTE ACCENT
  #x02DF ; Sk         MODIFIER LETTER CROSS ACCENT
  #x0391 ; Lu    [17] GREEK CAPITAL LETTER ALPHA..GREEK CAPITAL LETTER RHO
  #x0392 ; Lu    [17] GREEK CAPITAL LETTER ALPHA..GREEK CAPITAL LETTER RHO
  #x0393 ; Lu    [17] GREEK CAPITAL LETTER ALPHA..GREEK CAPITAL LETTER RHO
  #x0394 ; Lu    [17] GREEK CAPITAL LETTER ALPHA..GREEK CAPITAL LETTER RHO
  #x0395 ; Lu    [17] GREEK CAPITAL LETTER ALPHA..GREEK CAPITAL LETTER RHO
  #x0396 ; Lu    [17] GREEK CAPITAL LETTER ALPHA..GREEK CAPITAL LETTER RHO
  #x0397 ; Lu    [17] GREEK CAPITAL LETTER ALPHA..GREEK CAPITAL LETTER RHO
  #x0398 ; Lu    [17] GREEK CAPITAL LETTER ALPHA..GREEK CAPITAL LETTER RHO
  #x0399 ; Lu    [17] GREEK CAPITAL LETTER ALPHA..GREEK CAPITAL LETTER RHO
  #x039A ; Lu    [17] GREEK CAPITAL LETTER ALPHA..GREEK CAPITAL LETTER RHO
  #x039B ; Lu    [17] GREEK CAPITAL LETTER ALPHA..GREEK CAPITAL LETTER RHO
  #x039C ; Lu    [17] GREEK CAPITAL LETTER ALPHA..GREEK CAPITAL LETTER RHO
  #x039D ; Lu    [17] GREEK CAPITAL LETTER ALPHA..GREEK CAPITAL LETTER RHO
  #x039E ; Lu    [17] GREEK CAPITAL LETTER ALPHA..GREEK CAPITAL LETTER RHO
  #x039F ; Lu    [17] GREEK CAPITAL LETTER ALPHA..GREEK CAPITAL LETTER RHO
  #x03A0 ; Lu    [17] GREEK CAPITAL LETTER ALPHA..GREEK CAPITAL LETTER RHO
  #x03A1 ; Lu    [17] GREEK CAPITAL LETTER ALPHA..GREEK CAPITAL LETTER RHO
  #x03A3 ; Lu     [7] GREEK CAPITAL LETTER SIGMA..GREEK CAPITAL LETTER OMEGA
  #x03A4 ; Lu     [7] GREEK CAPITAL LETTER SIGMA..GREEK CAPITAL LETTER OMEGA
  #x03A5 ; Lu     [7] GREEK CAPITAL LETTER SIGMA..GREEK CAPITAL LETTER OMEGA
  #x03A6 ; Lu     [7] GREEK CAPITAL LETTER SIGMA..GREEK CAPITAL LETTER OMEGA
  #x03A7 ; Lu     [7] GREEK CAPITAL LETTER SIGMA..GREEK CAPITAL LETTER OMEGA
  #x03A8 ; Lu     [7] GREEK CAPITAL LETTER SIGMA..GREEK CAPITAL LETTER OMEGA
  #x03A9 ; Lu     [7] GREEK CAPITAL LETTER SIGMA..GREEK CAPITAL LETTER OMEGA
  #x03B1 ; Ll    [17] GREEK SMALL LETTER ALPHA..GREEK SMALL LETTER RHO
  #x03B2 ; Ll    [17] GREEK SMALL LETTER ALPHA..GREEK SMALL LETTER RHO
  #x03B3 ; Ll    [17] GREEK SMALL LETTER ALPHA..GREEK SMALL LETTER RHO
  #x03B4 ; Ll    [17] GREEK SMALL LETTER ALPHA..GREEK SMALL LETTER RHO
  #x03B5 ; Ll    [17] GREEK SMALL LETTER ALPHA..GREEK SMALL LETTER RHO
  #x03B6 ; Ll    [17] GREEK SMALL LETTER ALPHA..GREEK SMALL LETTER RHO
  #x03B7 ; Ll    [17] GREEK SMALL LETTER ALPHA..GREEK SMALL LETTER RHO
  #x03B8 ; Ll    [17] GREEK SMALL LETTER ALPHA..GREEK SMALL LETTER RHO
  #x03B9 ; Ll    [17] GREEK SMALL LETTER ALPHA..GREEK SMALL LETTER RHO
  #x03BA ; Ll    [17] GREEK SMALL LETTER ALPHA..GREEK SMALL LETTER RHO
  #x03BB ; Ll    [17] GREEK SMALL LETTER ALPHA..GREEK SMALL LETTER RHO
  #x03BC ; Ll    [17] GREEK SMALL LETTER ALPHA..GREEK SMALL LETTER RHO
  #x03BD ; Ll    [17] GREEK SMALL LETTER ALPHA..GREEK SMALL LETTER RHO
  #x03BE ; Ll    [17] GREEK SMALL LETTER ALPHA..GREEK SMALL LETTER RHO
  #x03BF ; Ll    [17] GREEK SMALL LETTER ALPHA..GREEK SMALL LETTER RHO
  #x03C0 ; Ll    [17] GREEK SMALL LETTER ALPHA..GREEK SMALL LETTER RHO
  #x03C1 ; Ll    [17] GREEK SMALL LETTER ALPHA..GREEK SMALL LETTER RHO
  #x03C3 ; Ll     [7] GREEK SMALL LETTER SIGMA..GREEK SMALL LETTER OMEGA
  #x03C4 ; Ll     [7] GREEK SMALL LETTER SIGMA..GREEK SMALL LETTER OMEGA
  #x03C5 ; Ll     [7] GREEK SMALL LETTER SIGMA..GREEK SMALL LETTER OMEGA
  #x03C6 ; Ll     [7] GREEK SMALL LETTER SIGMA..GREEK SMALL LETTER OMEGA
  #x03C7 ; Ll     [7] GREEK SMALL LETTER SIGMA..GREEK SMALL LETTER OMEGA
  #x03C8 ; Ll     [7] GREEK SMALL LETTER SIGMA..GREEK SMALL LETTER OMEGA
  #x03C9 ; Ll     [7] GREEK SMALL LETTER SIGMA..GREEK SMALL LETTER OMEGA
  #x0401 ; Lu         CYRILLIC CAPITAL LETTER IO
  #x0410 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0411 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0412 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0413 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0414 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0415 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0416 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0417 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0418 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0419 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x041A ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x041B ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x041C ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x041D ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x041E ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x041F ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0420 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0421 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0422 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0423 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0424 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0425 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0426 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0427 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0428 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0429 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x042A ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x042B ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x042C ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x042D ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x042E ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x042F ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0430 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0431 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0432 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0433 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0434 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0435 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0436 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0437 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0438 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0439 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x043A ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x043B ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x043C ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x043D ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x043E ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x043F ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0440 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0441 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0442 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0443 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0444 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0445 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0446 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0447 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0448 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0449 ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x044A ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x044B ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x044C ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x044D ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x044E ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x044F ; L&    [64] CYRILLIC CAPITAL LETTER A..CYRILLIC SMALL LETTER YA
  #x0451 ; Ll         CYRILLIC SMALL LETTER IO
  #x2010 ; Pd         HYPHEN
  #x2013 ; Pd     [3] EN DASH..HORIZONTAL BAR
  #x2014 ; Pd     [3] EN DASH..HORIZONTAL BAR
  #x2015 ; Pd     [3] EN DASH..HORIZONTAL BAR
  #x2016 ; Po         DOUBLE VERTICAL LINE
  #x2018 ; Pi         LEFT SINGLE QUOTATION MARK
  #x2019 ; Pf         RIGHT SINGLE QUOTATION MARK
  #x201C ; Pi         LEFT DOUBLE QUOTATION MARK
  #x201D ; Pf         RIGHT DOUBLE QUOTATION MARK
  #x2020 ; Po     [3] DAGGER..BULLET
  #x2021 ; Po     [3] DAGGER..BULLET
  #x2022 ; Po     [3] DAGGER..BULLET
  #x2024 ; Po     [4] ONE DOT LEADER..HYPHENATION POINT
  #x2025 ; Po     [4] ONE DOT LEADER..HYPHENATION POINT
  #x2026 ; Po     [4] ONE DOT LEADER..HYPHENATION POINT
  #x2027 ; Po     [4] ONE DOT LEADER..HYPHENATION POINT
  #x2030 ; Po         PER MILLE SIGN
  #x2032 ; Po     [2] PRIME..DOUBLE PRIME
  #x2033 ; Po     [2] PRIME..DOUBLE PRIME
  #x2035 ; Po         REVERSED PRIME
  #x203B ; Po         REFERENCE MARK
  #x203E ; Po         OVERLINE
  #x2074 ; No         SUPERSCRIPT FOUR
  #x207F ; Lm         SUPERSCRIPT LATIN SMALL LETTER N
  #x2081 ; No     [4] SUBSCRIPT ONE..SUBSCRIPT FOUR
  #x2082 ; No     [4] SUBSCRIPT ONE..SUBSCRIPT FOUR
  #x2083 ; No     [4] SUBSCRIPT ONE..SUBSCRIPT FOUR
  #x2084 ; No     [4] SUBSCRIPT ONE..SUBSCRIPT FOUR
  #x20AC ; Sc         EURO SIGN
  #x2103 ; So         DEGREE CELSIUS
  #x2105 ; So         CARE OF
  #x2109 ; So         DEGREE FAHRENHEIT
  #x2113 ; Ll         SCRIPT SMALL L
  #x2116 ; So         NUMERO SIGN
  #x2121 ; So     [2] TELEPHONE SIGN..TRADE MARK SIGN
  #x2122 ; So     [2] TELEPHONE SIGN..TRADE MARK SIGN
  #x2126 ; Lu         OHM SIGN
  #x212B ; Lu         ANGSTROM SIGN
  #x2153 ; No     [2] VULGAR FRACTION ONE THIRD..VULGAR FRACTION TWO THIRDS
  #x2154 ; No     [2] VULGAR FRACTION ONE THIRD..VULGAR FRACTION TWO THIRDS
  #x215B ; No     [4] VULGAR FRACTION ONE EIGHTH..VULGAR FRACTION SEVEN EIGHTHS
  #x215C ; No     [4] VULGAR FRACTION ONE EIGHTH..VULGAR FRACTION SEVEN EIGHTHS
  #x215D ; No     [4] VULGAR FRACTION ONE EIGHTH..VULGAR FRACTION SEVEN EIGHTHS
  #x215E ; No     [4] VULGAR FRACTION ONE EIGHTH..VULGAR FRACTION SEVEN EIGHTHS
  #x2160 ; Nl    [12] ROMAN NUMERAL ONE..ROMAN NUMERAL TWELVE
  #x2161 ; Nl    [12] ROMAN NUMERAL ONE..ROMAN NUMERAL TWELVE
  #x2162 ; Nl    [12] ROMAN NUMERAL ONE..ROMAN NUMERAL TWELVE
  #x2163 ; Nl    [12] ROMAN NUMERAL ONE..ROMAN NUMERAL TWELVE
  #x2164 ; Nl    [12] ROMAN NUMERAL ONE..ROMAN NUMERAL TWELVE
  #x2165 ; Nl    [12] ROMAN NUMERAL ONE..ROMAN NUMERAL TWELVE
  #x2166 ; Nl    [12] ROMAN NUMERAL ONE..ROMAN NUMERAL TWELVE
  #x2167 ; Nl    [12] ROMAN NUMERAL ONE..ROMAN NUMERAL TWELVE
  #x2168 ; Nl    [12] ROMAN NUMERAL ONE..ROMAN NUMERAL TWELVE
  #x2169 ; Nl    [12] ROMAN NUMERAL ONE..ROMAN NUMERAL TWELVE
  #x216A ; Nl    [12] ROMAN NUMERAL ONE..ROMAN NUMERAL TWELVE
  #x216B ; Nl    [12] ROMAN NUMERAL ONE..ROMAN NUMERAL TWELVE
  #x2170 ; Nl    [10] SMALL ROMAN NUMERAL ONE..SMALL ROMAN NUMERAL TEN
  #x2171 ; Nl    [10] SMALL ROMAN NUMERAL ONE..SMALL ROMAN NUMERAL TEN
  #x2172 ; Nl    [10] SMALL ROMAN NUMERAL ONE..SMALL ROMAN NUMERAL TEN
  #x2173 ; Nl    [10] SMALL ROMAN NUMERAL ONE..SMALL ROMAN NUMERAL TEN
  #x2174 ; Nl    [10] SMALL ROMAN NUMERAL ONE..SMALL ROMAN NUMERAL TEN
  #x2175 ; Nl    [10] SMALL ROMAN NUMERAL ONE..SMALL ROMAN NUMERAL TEN
  #x2176 ; Nl    [10] SMALL ROMAN NUMERAL ONE..SMALL ROMAN NUMERAL TEN
  #x2177 ; Nl    [10] SMALL ROMAN NUMERAL ONE..SMALL ROMAN NUMERAL TEN
  #x2178 ; Nl    [10] SMALL ROMAN NUMERAL ONE..SMALL ROMAN NUMERAL TEN
  #x2179 ; Nl    [10] SMALL ROMAN NUMERAL ONE..SMALL ROMAN NUMERAL TEN
  #x2189 ; No         VULGAR FRACTION ZERO THIRDS
  #x2190 ; Sm     [5] LEFTWARDS ARROW..LEFT RIGHT ARROW
  #x2191 ; Sm     [5] LEFTWARDS ARROW..LEFT RIGHT ARROW
  #x2192 ; Sm     [5] LEFTWARDS ARROW..LEFT RIGHT ARROW
  #x2193 ; Sm     [5] LEFTWARDS ARROW..LEFT RIGHT ARROW
  #x2194 ; Sm     [5] LEFTWARDS ARROW..LEFT RIGHT ARROW
  #x2195 ; So     [5] UP DOWN ARROW..SOUTH WEST ARROW
  #x2196 ; So     [5] UP DOWN ARROW..SOUTH WEST ARROW
  #x2197 ; So     [5] UP DOWN ARROW..SOUTH WEST ARROW
  #x2198 ; So     [5] UP DOWN ARROW..SOUTH WEST ARROW
  #x2199 ; So     [5] UP DOWN ARROW..SOUTH WEST ARROW
  #x21B8 ; So     [2] NORTH WEST ARROW TO LONG BAR..LEFTWARDS ARROW TO BAR OVER RIGHTWARDS ARROW TO BAR
  #x21B9 ; So     [2] NORTH WEST ARROW TO LONG BAR..LEFTWARDS ARROW TO BAR OVER RIGHTWARDS ARROW TO BAR
  #x21D2 ; Sm         RIGHTWARDS DOUBLE ARROW
  #x21D4 ; Sm         LEFT RIGHT DOUBLE ARROW
  #x21E7 ; So         UPWARDS WHITE ARROW
  #x2200 ; Sm         FOR ALL
  #x2202 ; Sm     [2] PARTIAL DIFFERENTIAL..THERE EXISTS
  #x2203 ; Sm     [2] PARTIAL DIFFERENTIAL..THERE EXISTS
  #x2207 ; Sm     [2] NABLA..ELEMENT OF
  #x2208 ; Sm     [2] NABLA..ELEMENT OF
  #x220B ; Sm         CONTAINS AS MEMBER
  #x220F ; Sm         N-ARY PRODUCT
  #x2211 ; Sm         N-ARY SUMMATION
  #x2215 ; Sm         DIVISION SLASH
  #x221A ; Sm         SQUARE ROOT
  #x221D ; Sm     [4] PROPORTIONAL TO..ANGLE
  #x221E ; Sm     [4] PROPORTIONAL TO..ANGLE
  #x221F ; Sm     [4] PROPORTIONAL TO..ANGLE
  #x2220 ; Sm     [4] PROPORTIONAL TO..ANGLE
  #x2223 ; Sm         DIVIDES
  #x2225 ; Sm         PARALLEL TO
  #x2227 ; Sm     [6] LOGICAL AND..DOUBLE INTEGRAL
  #x2228 ; Sm     [6] LOGICAL AND..DOUBLE INTEGRAL
  #x2229 ; Sm     [6] LOGICAL AND..DOUBLE INTEGRAL
  #x222A ; Sm     [6] LOGICAL AND..DOUBLE INTEGRAL
  #x222B ; Sm     [6] LOGICAL AND..DOUBLE INTEGRAL
  #x222C ; Sm     [6] LOGICAL AND..DOUBLE INTEGRAL
  #x222E ; Sm         CONTOUR INTEGRAL
  #x2234 ; Sm     [4] THEREFORE..PROPORTION
  #x2235 ; Sm     [4] THEREFORE..PROPORTION
  #x2236 ; Sm     [4] THEREFORE..PROPORTION
  #x2237 ; Sm     [4] THEREFORE..PROPORTION
  #x223C ; Sm     [2] TILDE OPERATOR..REVERSED TILDE
  #x223D ; Sm     [2] TILDE OPERATOR..REVERSED TILDE
  #x2248 ; Sm         ALMOST EQUAL TO
  #x224C ; Sm         ALL EQUAL TO
  #x2252 ; Sm         APPROXIMATELY EQUAL TO OR THE IMAGE OF
  #x2260 ; Sm     [2] NOT EQUAL TO..IDENTICAL TO
  #x2261 ; Sm     [2] NOT EQUAL TO..IDENTICAL TO
  #x2264 ; Sm     [4] LESS-THAN OR EQUAL TO..GREATER-THAN OVER EQUAL TO
  #x2265 ; Sm     [4] LESS-THAN OR EQUAL TO..GREATER-THAN OVER EQUAL TO
  #x2266 ; Sm     [4] LESS-THAN OR EQUAL TO..GREATER-THAN OVER EQUAL TO
  #x2267 ; Sm     [4] LESS-THAN OR EQUAL TO..GREATER-THAN OVER EQUAL TO
  #x226A ; Sm     [2] MUCH LESS-THAN..MUCH GREATER-THAN
  #x226B ; Sm     [2] MUCH LESS-THAN..MUCH GREATER-THAN
  #x226E ; Sm     [2] NOT LESS-THAN..NOT GREATER-THAN
  #x226F ; Sm     [2] NOT LESS-THAN..NOT GREATER-THAN
  #x2282 ; Sm     [2] SUBSET OF..SUPERSET OF
  #x2283 ; Sm     [2] SUBSET OF..SUPERSET OF
  #x2286 ; Sm     [2] SUBSET OF OR EQUAL TO..SUPERSET OF OR EQUAL TO
  #x2287 ; Sm     [2] SUBSET OF OR EQUAL TO..SUPERSET OF OR EQUAL TO
  #x2295 ; Sm         CIRCLED PLUS
  #x2299 ; Sm         CIRCLED DOT OPERATOR
  #x22A5 ; Sm         UP TACK
  #x22BF ; Sm         RIGHT TRIANGLE
  #x2312 ; So         ARC
  #x2460 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x2461 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x2462 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x2463 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x2464 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x2465 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x2466 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x2467 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x2468 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x2469 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x246A ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x246B ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x246C ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x246D ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x246E ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x246F ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x2470 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x2471 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x2472 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x2473 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x2474 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x2475 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x2476 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x2477 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x2478 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x2479 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x247A ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x247B ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x247C ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x247D ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x247E ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x247F ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x2480 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x2481 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x2482 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x2483 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x2484 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x2485 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x2486 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x2487 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x2488 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x2489 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x248A ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x248B ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x248C ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x248D ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x248E ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x248F ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x2490 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x2491 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x2492 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x2493 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x2494 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x2495 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x2496 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x2497 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x2498 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x2499 ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x249A ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x249B ; No    [60] CIRCLED DIGIT ONE..NUMBER TWENTY FULL STOP
  #x249C ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x249D ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x249E ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x249F ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24A0 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24A1 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24A2 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24A3 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24A4 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24A5 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24A6 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24A7 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24A8 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24A9 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24AA ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24AB ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24AC ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24AD ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24AE ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24AF ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24B0 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24B1 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24B2 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24B3 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24B4 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24B5 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24B6 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24B7 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24B8 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24B9 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24BA ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24BB ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24BC ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24BD ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24BE ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24BF ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24C0 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24C1 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24C2 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24C3 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24C4 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24C5 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24C6 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24C7 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24C8 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24C9 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24CA ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24CB ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24CC ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24CD ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24CE ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24CF ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24D0 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24D1 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24D2 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24D3 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24D4 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24D5 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24D6 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24D7 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24D8 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24D9 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24DA ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24DB ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24DC ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24DD ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24DE ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24DF ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24E0 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24E1 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24E2 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24E3 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24E4 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24E5 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24E6 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24E7 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24E8 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24E9 ; So    [78] PARENTHESIZED LATIN SMALL LETTER A..CIRCLED LATIN SMALL LETTER Z
  #x24EB ; No    [21] NEGATIVE CIRCLED NUMBER ELEVEN..NEGATIVE CIRCLED DIGIT ZERO
  #x24EC ; No    [21] NEGATIVE CIRCLED NUMBER ELEVEN..NEGATIVE CIRCLED DIGIT ZERO
  #x24ED ; No    [21] NEGATIVE CIRCLED NUMBER ELEVEN..NEGATIVE CIRCLED DIGIT ZERO
  #x24EE ; No    [21] NEGATIVE CIRCLED NUMBER ELEVEN..NEGATIVE CIRCLED DIGIT ZERO
  #x24EF ; No    [21] NEGATIVE CIRCLED NUMBER ELEVEN..NEGATIVE CIRCLED DIGIT ZERO
  #x24F0 ; No    [21] NEGATIVE CIRCLED NUMBER ELEVEN..NEGATIVE CIRCLED DIGIT ZERO
  #x24F1 ; No    [21] NEGATIVE CIRCLED NUMBER ELEVEN..NEGATIVE CIRCLED DIGIT ZERO
  #x24F2 ; No    [21] NEGATIVE CIRCLED NUMBER ELEVEN..NEGATIVE CIRCLED DIGIT ZERO
  #x24F3 ; No    [21] NEGATIVE CIRCLED NUMBER ELEVEN..NEGATIVE CIRCLED DIGIT ZERO
  #x24F4 ; No    [21] NEGATIVE CIRCLED NUMBER ELEVEN..NEGATIVE CIRCLED DIGIT ZERO
  #x24F5 ; No    [21] NEGATIVE CIRCLED NUMBER ELEVEN..NEGATIVE CIRCLED DIGIT ZERO
  #x24F6 ; No    [21] NEGATIVE CIRCLED NUMBER ELEVEN..NEGATIVE CIRCLED DIGIT ZERO
  #x24F7 ; No    [21] NEGATIVE CIRCLED NUMBER ELEVEN..NEGATIVE CIRCLED DIGIT ZERO
  #x24F8 ; No    [21] NEGATIVE CIRCLED NUMBER ELEVEN..NEGATIVE CIRCLED DIGIT ZERO
  #x24F9 ; No    [21] NEGATIVE CIRCLED NUMBER ELEVEN..NEGATIVE CIRCLED DIGIT ZERO
  #x24FA ; No    [21] NEGATIVE CIRCLED NUMBER ELEVEN..NEGATIVE CIRCLED DIGIT ZERO
  #x24FB ; No    [21] NEGATIVE CIRCLED NUMBER ELEVEN..NEGATIVE CIRCLED DIGIT ZERO
  #x24FC ; No    [21] NEGATIVE CIRCLED NUMBER ELEVEN..NEGATIVE CIRCLED DIGIT ZERO
  #x24FD ; No    [21] NEGATIVE CIRCLED NUMBER ELEVEN..NEGATIVE CIRCLED DIGIT ZERO
  #x24FE ; No    [21] NEGATIVE CIRCLED NUMBER ELEVEN..NEGATIVE CIRCLED DIGIT ZERO
  #x24FF ; No    [21] NEGATIVE CIRCLED NUMBER ELEVEN..NEGATIVE CIRCLED DIGIT ZERO
  #x2500 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2501 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2502 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2503 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2504 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2505 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2506 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2507 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2508 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2509 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x250A ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x250B ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x250C ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x250D ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x250E ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x250F ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2510 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2511 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2512 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2513 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2514 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2515 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2516 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2517 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2518 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2519 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x251A ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x251B ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x251C ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x251D ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x251E ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x251F ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2520 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2521 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2522 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2523 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2524 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2525 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2526 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2527 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2528 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2529 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x252A ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x252B ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x252C ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x252D ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x252E ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x252F ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2530 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2531 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2532 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2533 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2534 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2535 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2536 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2537 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2538 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2539 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x253A ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x253B ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x253C ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x253D ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x253E ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x253F ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2540 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2541 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2542 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2543 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2544 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2545 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2546 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2547 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2548 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2549 ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x254A ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x254B ; So    [76] BOX DRAWINGS LIGHT HORIZONTAL..BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
  #x2550 ; So    [36] BOX DRAWINGS DOUBLE HORIZONTAL..BOX DRAWINGS LIGHT DIAGONAL CROSS
  #x2551 ; So    [36] BOX DRAWINGS DOUBLE HORIZONTAL..BOX DRAWINGS LIGHT DIAGONAL CROSS
  #x2552 ; So    [36] BOX DRAWINGS DOUBLE HORIZONTAL..BOX DRAWINGS LIGHT DIAGONAL CROSS
  #x2553 ; So    [36] BOX DRAWINGS DOUBLE HORIZONTAL..BOX DRAWINGS LIGHT DIAGONAL CROSS
  #x2554 ; So    [36] BOX DRAWINGS DOUBLE HORIZONTAL..BOX DRAWINGS LIGHT DIAGONAL CROSS
  #x2555 ; So    [36] BOX DRAWINGS DOUBLE HORIZONTAL..BOX DRAWINGS LIGHT DIAGONAL CROSS
  #x2556 ; So    [36] BOX DRAWINGS DOUBLE HORIZONTAL..BOX DRAWINGS LIGHT DIAGONAL CROSS
  #x2557 ; So    [36] BOX DRAWINGS DOUBLE HORIZONTAL..BOX DRAWINGS LIGHT DIAGONAL CROSS
  #x2558 ; So    [36] BOX DRAWINGS DOUBLE HORIZONTAL..BOX DRAWINGS LIGHT DIAGONAL CROSS
  #x2559 ; So    [36] BOX DRAWINGS DOUBLE HORIZONTAL..BOX DRAWINGS LIGHT DIAGONAL CROSS
  #x255A ; So    [36] BOX DRAWINGS DOUBLE HORIZONTAL..BOX DRAWINGS LIGHT DIAGONAL CROSS
  #x255B ; So    [36] BOX DRAWINGS DOUBLE HORIZONTAL..BOX DRAWINGS LIGHT DIAGONAL CROSS
  #x255C ; So    [36] BOX DRAWINGS DOUBLE HORIZONTAL..BOX DRAWINGS LIGHT DIAGONAL CROSS
  #x255D ; So    [36] BOX DRAWINGS DOUBLE HORIZONTAL..BOX DRAWINGS LIGHT DIAGONAL CROSS
  #x255E ; So    [36] BOX DRAWINGS DOUBLE HORIZONTAL..BOX DRAWINGS LIGHT DIAGONAL CROSS
  #x255F ; So    [36] BOX DRAWINGS DOUBLE HORIZONTAL..BOX DRAWINGS LIGHT DIAGONAL CROSS
  #x2560 ; So    [36] BOX DRAWINGS DOUBLE HORIZONTAL..BOX DRAWINGS LIGHT DIAGONAL CROSS
  #x2561 ; So    [36] BOX DRAWINGS DOUBLE HORIZONTAL..BOX DRAWINGS LIGHT DIAGONAL CROSS
  #x2562 ; So    [36] BOX DRAWINGS DOUBLE HORIZONTAL..BOX DRAWINGS LIGHT DIAGONAL CROSS
  #x2563 ; So    [36] BOX DRAWINGS DOUBLE HORIZONTAL..BOX DRAWINGS LIGHT DIAGONAL CROSS
  #x2564 ; So    [36] BOX DRAWINGS DOUBLE HORIZONTAL..BOX DRAWINGS LIGHT DIAGONAL CROSS
  #x2565 ; So    [36] BOX DRAWINGS DOUBLE HORIZONTAL..BOX DRAWINGS LIGHT DIAGONAL CROSS
  #x2566 ; So    [36] BOX DRAWINGS DOUBLE HORIZONTAL..BOX DRAWINGS LIGHT DIAGONAL CROSS
  #x2567 ; So    [36] BOX DRAWINGS DOUBLE HORIZONTAL..BOX DRAWINGS LIGHT DIAGONAL CROSS
  #x2568 ; So    [36] BOX DRAWINGS DOUBLE HORIZONTAL..BOX DRAWINGS LIGHT DIAGONAL CROSS
  #x2569 ; So    [36] BOX DRAWINGS DOUBLE HORIZONTAL..BOX DRAWINGS LIGHT DIAGONAL CROSS
  #x256A ; So    [36] BOX DRAWINGS DOUBLE HORIZONTAL..BOX DRAWINGS LIGHT DIAGONAL CROSS
  #x256B ; So    [36] BOX DRAWINGS DOUBLE HORIZONTAL..BOX DRAWINGS LIGHT DIAGONAL CROSS
  #x256C ; So    [36] BOX DRAWINGS DOUBLE HORIZONTAL..BOX DRAWINGS LIGHT DIAGONAL CROSS
  #x256D ; So    [36] BOX DRAWINGS DOUBLE HORIZONTAL..BOX DRAWINGS LIGHT DIAGONAL CROSS
  #x256E ; So    [36] BOX DRAWINGS DOUBLE HORIZONTAL..BOX DRAWINGS LIGHT DIAGONAL CROSS
  #x256F ; So    [36] BOX DRAWINGS DOUBLE HORIZONTAL..BOX DRAWINGS LIGHT DIAGONAL CROSS
  #x2570 ; So    [36] BOX DRAWINGS DOUBLE HORIZONTAL..BOX DRAWINGS LIGHT DIAGONAL CROSS
  #x2571 ; So    [36] BOX DRAWINGS DOUBLE HORIZONTAL..BOX DRAWINGS LIGHT DIAGONAL CROSS
  #x2572 ; So    [36] BOX DRAWINGS DOUBLE HORIZONTAL..BOX DRAWINGS LIGHT DIAGONAL CROSS
  #x2573 ; So    [36] BOX DRAWINGS DOUBLE HORIZONTAL..BOX DRAWINGS LIGHT DIAGONAL CROSS
  #x2580 ; So    [16] UPPER HALF BLOCK..LEFT ONE EIGHTH BLOCK
  #x2581 ; So    [16] UPPER HALF BLOCK..LEFT ONE EIGHTH BLOCK
  #x2582 ; So    [16] UPPER HALF BLOCK..LEFT ONE EIGHTH BLOCK
  #x2583 ; So    [16] UPPER HALF BLOCK..LEFT ONE EIGHTH BLOCK
  #x2584 ; So    [16] UPPER HALF BLOCK..LEFT ONE EIGHTH BLOCK
  #x2585 ; So    [16] UPPER HALF BLOCK..LEFT ONE EIGHTH BLOCK
  #x2586 ; So    [16] UPPER HALF BLOCK..LEFT ONE EIGHTH BLOCK
  #x2587 ; So    [16] UPPER HALF BLOCK..LEFT ONE EIGHTH BLOCK
  #x2588 ; So    [16] UPPER HALF BLOCK..LEFT ONE EIGHTH BLOCK
  #x2589 ; So    [16] UPPER HALF BLOCK..LEFT ONE EIGHTH BLOCK
  #x258A ; So    [16] UPPER HALF BLOCK..LEFT ONE EIGHTH BLOCK
  #x258B ; So    [16] UPPER HALF BLOCK..LEFT ONE EIGHTH BLOCK
  #x258C ; So    [16] UPPER HALF BLOCK..LEFT ONE EIGHTH BLOCK
  #x258D ; So    [16] UPPER HALF BLOCK..LEFT ONE EIGHTH BLOCK
  #x258E ; So    [16] UPPER HALF BLOCK..LEFT ONE EIGHTH BLOCK
  #x258F ; So    [16] UPPER HALF BLOCK..LEFT ONE EIGHTH BLOCK
  #x2592 ; So     [4] MEDIUM SHADE..RIGHT ONE EIGHTH BLOCK
  #x2593 ; So     [4] MEDIUM SHADE..RIGHT ONE EIGHTH BLOCK
  #x2594 ; So     [4] MEDIUM SHADE..RIGHT ONE EIGHTH BLOCK
  #x2595 ; So     [4] MEDIUM SHADE..RIGHT ONE EIGHTH BLOCK
  #x25A0 ; So     [2] BLACK SQUARE..WHITE SQUARE
  #x25A1 ; So     [2] BLACK SQUARE..WHITE SQUARE
  #x25A3 ; So     [7] WHITE SQUARE CONTAINING BLACK SMALL SQUARE..SQUARE WITH DIAGONAL CROSSHATCH FILL
  #x25A4 ; So     [7] WHITE SQUARE CONTAINING BLACK SMALL SQUARE..SQUARE WITH DIAGONAL CROSSHATCH FILL
  #x25A5 ; So     [7] WHITE SQUARE CONTAINING BLACK SMALL SQUARE..SQUARE WITH DIAGONAL CROSSHATCH FILL
  #x25A6 ; So     [7] WHITE SQUARE CONTAINING BLACK SMALL SQUARE..SQUARE WITH DIAGONAL CROSSHATCH FILL
  #x25A7 ; So     [7] WHITE SQUARE CONTAINING BLACK SMALL SQUARE..SQUARE WITH DIAGONAL CROSSHATCH FILL
  #x25A8 ; So     [7] WHITE SQUARE CONTAINING BLACK SMALL SQUARE..SQUARE WITH DIAGONAL CROSSHATCH FILL
  #x25A9 ; So     [7] WHITE SQUARE CONTAINING BLACK SMALL SQUARE..SQUARE WITH DIAGONAL CROSSHATCH FILL
  #x25B2 ; So     [2] BLACK UP-POINTING TRIANGLE..WHITE UP-POINTING TRIANGLE
  #x25B3 ; So     [2] BLACK UP-POINTING TRIANGLE..WHITE UP-POINTING TRIANGLE
  #x25B6 ; So         BLACK RIGHT-POINTING TRIANGLE
  #x25B7 ; Sm         WHITE RIGHT-POINTING TRIANGLE
  #x25BC ; So     [2] BLACK DOWN-POINTING TRIANGLE..WHITE DOWN-POINTING TRIANGLE
  #x25BD ; So     [2] BLACK DOWN-POINTING TRIANGLE..WHITE DOWN-POINTING TRIANGLE
  #x25C0 ; So         BLACK LEFT-POINTING TRIANGLE
  #x25C1 ; Sm         WHITE LEFT-POINTING TRIANGLE
  #x25C6 ; So     [3] BLACK DIAMOND..WHITE DIAMOND CONTAINING BLACK SMALL DIAMOND
  #x25C7 ; So     [3] BLACK DIAMOND..WHITE DIAMOND CONTAINING BLACK SMALL DIAMOND
  #x25C8 ; So     [3] BLACK DIAMOND..WHITE DIAMOND CONTAINING BLACK SMALL DIAMOND
  #x25CB ; So         WHITE CIRCLE
  #x25CE ; So     [4] BULLSEYE..CIRCLE WITH RIGHT HALF BLACK
  #x25CF ; So     [4] BULLSEYE..CIRCLE WITH RIGHT HALF BLACK
  #x25D0 ; So     [4] BULLSEYE..CIRCLE WITH RIGHT HALF BLACK
  #x25D1 ; So     [4] BULLSEYE..CIRCLE WITH RIGHT HALF BLACK
  #x25E2 ; So     [4] BLACK LOWER RIGHT TRIANGLE..BLACK UPPER RIGHT TRIANGLE
  #x25E3 ; So     [4] BLACK LOWER RIGHT TRIANGLE..BLACK UPPER RIGHT TRIANGLE
  #x25E4 ; So     [4] BLACK LOWER RIGHT TRIANGLE..BLACK UPPER RIGHT TRIANGLE
  #x25E5 ; So     [4] BLACK LOWER RIGHT TRIANGLE..BLACK UPPER RIGHT TRIANGLE
  #x25EF ; So         LARGE CIRCLE
  #x2605 ; So     [2] BLACK STAR..WHITE STAR
  #x2606 ; So     [2] BLACK STAR..WHITE STAR
  #x2609 ; So         SUN
  #x260E ; So     [2] BLACK TELEPHONE..WHITE TELEPHONE
  #x260F ; So     [2] BLACK TELEPHONE..WHITE TELEPHONE
  #x261C ; So         WHITE LEFT POINTING INDEX
  #x261E ; So         WHITE RIGHT POINTING INDEX
  #x2640 ; So         FEMALE SIGN
  #x2642 ; So         MALE SIGN
  #x2660 ; So     [2] BLACK SPADE SUIT..WHITE HEART SUIT
  #x2661 ; So     [2] BLACK SPADE SUIT..WHITE HEART SUIT
  #x2663 ; So     [3] BLACK CLUB SUIT..BLACK HEART SUIT
  #x2664 ; So     [3] BLACK CLUB SUIT..BLACK HEART SUIT
  #x2665 ; So     [3] BLACK CLUB SUIT..BLACK HEART SUIT
  #x2667 ; So     [4] WHITE CLUB SUIT..EIGHTH NOTE
  #x2668 ; So     [4] WHITE CLUB SUIT..EIGHTH NOTE
  #x2669 ; So     [4] WHITE CLUB SUIT..EIGHTH NOTE
  #x266A ; So     [4] WHITE CLUB SUIT..EIGHTH NOTE
  #x266C ; So     [2] BEAMED SIXTEENTH NOTES..MUSIC FLAT SIGN
  #x266D ; So     [2] BEAMED SIXTEENTH NOTES..MUSIC FLAT SIGN
  #x266F ; Sm         MUSIC SHARP SIGN
  #x269E ; So     [2] THREE LINES CONVERGING RIGHT..THREE LINES CONVERGING LEFT
  #x269F ; So     [2] THREE LINES CONVERGING RIGHT..THREE LINES CONVERGING LEFT
  #x26BF ; So         SQUARED KEY
  #x26C6 ; So     [8] RAIN..DISABLED CAR
  #x26C7 ; So     [8] RAIN..DISABLED CAR
  #x26C8 ; So     [8] RAIN..DISABLED CAR
  #x26C9 ; So     [8] RAIN..DISABLED CAR
  #x26CA ; So     [8] RAIN..DISABLED CAR
  #x26CB ; So     [8] RAIN..DISABLED CAR
  #x26CC ; So     [8] RAIN..DISABLED CAR
  #x26CD ; So     [8] RAIN..DISABLED CAR
  #x26CF ; So     [5] PICK..CHAINS
  #x26D0 ; So     [5] PICK..CHAINS
  #x26D1 ; So     [5] PICK..CHAINS
  #x26D2 ; So     [5] PICK..CHAINS
  #x26D3 ; So     [5] PICK..CHAINS
  #x26D5 ; So    [13] ALTERNATE ONE-WAY LEFT WAY TRAFFIC..RESTRICTED LEFT ENTRY-2
  #x26D6 ; So    [13] ALTERNATE ONE-WAY LEFT WAY TRAFFIC..RESTRICTED LEFT ENTRY-2
  #x26D7 ; So    [13] ALTERNATE ONE-WAY LEFT WAY TRAFFIC..RESTRICTED LEFT ENTRY-2
  #x26D8 ; So    [13] ALTERNATE ONE-WAY LEFT WAY TRAFFIC..RESTRICTED LEFT ENTRY-2
  #x26D9 ; So    [13] ALTERNATE ONE-WAY LEFT WAY TRAFFIC..RESTRICTED LEFT ENTRY-2
  #x26DA ; So    [13] ALTERNATE ONE-WAY LEFT WAY TRAFFIC..RESTRICTED LEFT ENTRY-2
  #x26DB ; So    [13] ALTERNATE ONE-WAY LEFT WAY TRAFFIC..RESTRICTED LEFT ENTRY-2
  #x26DC ; So    [13] ALTERNATE ONE-WAY LEFT WAY TRAFFIC..RESTRICTED LEFT ENTRY-2
  #x26DD ; So    [13] ALTERNATE ONE-WAY LEFT WAY TRAFFIC..RESTRICTED LEFT ENTRY-2
  #x26DE ; So    [13] ALTERNATE ONE-WAY LEFT WAY TRAFFIC..RESTRICTED LEFT ENTRY-2
  #x26DF ; So    [13] ALTERNATE ONE-WAY LEFT WAY TRAFFIC..RESTRICTED LEFT ENTRY-2
  #x26E0 ; So    [13] ALTERNATE ONE-WAY LEFT WAY TRAFFIC..RESTRICTED LEFT ENTRY-2
  #x26E1 ; So    [13] ALTERNATE ONE-WAY LEFT WAY TRAFFIC..RESTRICTED LEFT ENTRY-2
  #x26E3 ; So         HEAVY CIRCLE WITH STROKE AND TWO DOTS ABOVE
  #x26E8 ; So     [2] BLACK CROSS ON SHIELD..SHINTO SHRINE
  #x26E9 ; So     [2] BLACK CROSS ON SHIELD..SHINTO SHRINE
  #x26EB ; So     [7] CASTLE..UMBRELLA ON GROUND
  #x26EC ; So     [7] CASTLE..UMBRELLA ON GROUND
  #x26ED ; So     [7] CASTLE..UMBRELLA ON GROUND
  #x26EE ; So     [7] CASTLE..UMBRELLA ON GROUND
  #x26EF ; So     [7] CASTLE..UMBRELLA ON GROUND
  #x26F0 ; So     [7] CASTLE..UMBRELLA ON GROUND
  #x26F1 ; So     [7] CASTLE..UMBRELLA ON GROUND
  #x26F4 ; So         FERRY
  #x26F6 ; So     [4] SQUARE FOUR CORNERS..PERSON WITH BALL
  #x26F7 ; So     [4] SQUARE FOUR CORNERS..PERSON WITH BALL
  #x26F8 ; So     [4] SQUARE FOUR CORNERS..PERSON WITH BALL
  #x26F9 ; So     [4] SQUARE FOUR CORNERS..PERSON WITH BALL
  #x26FB ; So     [2] JAPANESE BANK SYMBOL..HEADSTONE GRAVEYARD SYMBOL
  #x26FC ; So     [2] JAPANESE BANK SYMBOL..HEADSTONE GRAVEYARD SYMBOL
  #x26FE ; So     [2] CUP ON BLACK SQUARE..WHITE FLAG WITH HORIZONTAL MIDDLE BLACK STRIPE
  #x26FF ; So     [2] CUP ON BLACK SQUARE..WHITE FLAG WITH HORIZONTAL MIDDLE BLACK STRIPE
  #x273D ; So         HEAVY TEARDROP-SPOKED ASTERISK
  #x2776 ; No    [10] DINGBAT NEGATIVE CIRCLED DIGIT ONE..DINGBAT NEGATIVE CIRCLED NUMBER TEN
  #x2777 ; No    [10] DINGBAT NEGATIVE CIRCLED DIGIT ONE..DINGBAT NEGATIVE CIRCLED NUMBER TEN
  #x2778 ; No    [10] DINGBAT NEGATIVE CIRCLED DIGIT ONE..DINGBAT NEGATIVE CIRCLED NUMBER TEN
  #x2779 ; No    [10] DINGBAT NEGATIVE CIRCLED DIGIT ONE..DINGBAT NEGATIVE CIRCLED NUMBER TEN
  #x277A ; No    [10] DINGBAT NEGATIVE CIRCLED DIGIT ONE..DINGBAT NEGATIVE CIRCLED NUMBER TEN
  #x277B ; No    [10] DINGBAT NEGATIVE CIRCLED DIGIT ONE..DINGBAT NEGATIVE CIRCLED NUMBER TEN
  #x277C ; No    [10] DINGBAT NEGATIVE CIRCLED DIGIT ONE..DINGBAT NEGATIVE CIRCLED NUMBER TEN
  #x277D ; No    [10] DINGBAT NEGATIVE CIRCLED DIGIT ONE..DINGBAT NEGATIVE CIRCLED NUMBER TEN
  #x277E ; No    [10] DINGBAT NEGATIVE CIRCLED DIGIT ONE..DINGBAT NEGATIVE CIRCLED NUMBER TEN
  #x277F ; No    [10] DINGBAT NEGATIVE CIRCLED DIGIT ONE..DINGBAT NEGATIVE CIRCLED NUMBER TEN
  #x2B56 ; So     [4] HEAVY OVAL WITH OVAL INSIDE..HEAVY CIRCLED SALTIRE
  #x2B57 ; So     [4] HEAVY OVAL WITH OVAL INSIDE..HEAVY CIRCLED SALTIRE
  #x2B58 ; So     [4] HEAVY OVAL WITH OVAL INSIDE..HEAVY CIRCLED SALTIRE
  #x2B59 ; So     [4] HEAVY OVAL WITH OVAL INSIDE..HEAVY CIRCLED SALTIRE
  #x3248 ; No     [8] CIRCLED NUMBER TEN ON BLACK SQUARE..CIRCLED NUMBER EIGHTY ON BLACK SQUARE
  #x3249 ; No     [8] CIRCLED NUMBER TEN ON BLACK SQUARE..CIRCLED NUMBER EIGHTY ON BLACK SQUARE
  #x324A ; No     [8] CIRCLED NUMBER TEN ON BLACK SQUARE..CIRCLED NUMBER EIGHTY ON BLACK SQUARE
  #x324B ; No     [8] CIRCLED NUMBER TEN ON BLACK SQUARE..CIRCLED NUMBER EIGHTY ON BLACK SQUARE
  #x324C ; No     [8] CIRCLED NUMBER TEN ON BLACK SQUARE..CIRCLED NUMBER EIGHTY ON BLACK SQUARE
  #x324D ; No     [8] CIRCLED NUMBER TEN ON BLACK SQUARE..CIRCLED NUMBER EIGHTY ON BLACK SQUARE
  #x324E ; No     [8] CIRCLED NUMBER TEN ON BLACK SQUARE..CIRCLED NUMBER EIGHTY ON BLACK SQUARE
  #x324F ; No     [8] CIRCLED NUMBER TEN ON BLACK SQUARE..CIRCLED NUMBER EIGHTY ON BLACK SQUARE
  #xFFFD ; So         REPLACEMENT CHARACTER
  #x1F100 ; No    [11] DIGIT ZERO FULL STOP..DIGIT NINE COMMA
  #x1F101 ; No    [11] DIGIT ZERO FULL STOP..DIGIT NINE COMMA
  #x1F102 ; No    [11] DIGIT ZERO FULL STOP..DIGIT NINE COMMA
  #x1F103 ; No    [11] DIGIT ZERO FULL STOP..DIGIT NINE COMMA
  #x1F104 ; No    [11] DIGIT ZERO FULL STOP..DIGIT NINE COMMA
  #x1F105 ; No    [11] DIGIT ZERO FULL STOP..DIGIT NINE COMMA
  #x1F106 ; No    [11] DIGIT ZERO FULL STOP..DIGIT NINE COMMA
  #x1F107 ; No    [11] DIGIT ZERO FULL STOP..DIGIT NINE COMMA
  #x1F108 ; No    [11] DIGIT ZERO FULL STOP..DIGIT NINE COMMA
  #x1F109 ; No    [11] DIGIT ZERO FULL STOP..DIGIT NINE COMMA
  #x1F10A ; No    [11] DIGIT ZERO FULL STOP..DIGIT NINE COMMA
  #x1F110 ; So    [30] PARENTHESIZED LATIN CAPITAL LETTER A..CIRCLED CD
  #x1F111 ; So    [30] PARENTHESIZED LATIN CAPITAL LETTER A..CIRCLED CD
  #x1F112 ; So    [30] PARENTHESIZED LATIN CAPITAL LETTER A..CIRCLED CD
  #x1F113 ; So    [30] PARENTHESIZED LATIN CAPITAL LETTER A..CIRCLED CD
  #x1F114 ; So    [30] PARENTHESIZED LATIN CAPITAL LETTER A..CIRCLED CD
  #x1F115 ; So    [30] PARENTHESIZED LATIN CAPITAL LETTER A..CIRCLED CD
  #x1F116 ; So    [30] PARENTHESIZED LATIN CAPITAL LETTER A..CIRCLED CD
  #x1F117 ; So    [30] PARENTHESIZED LATIN CAPITAL LETTER A..CIRCLED CD
  #x1F118 ; So    [30] PARENTHESIZED LATIN CAPITAL LETTER A..CIRCLED CD
  #x1F119 ; So    [30] PARENTHESIZED LATIN CAPITAL LETTER A..CIRCLED CD
  #x1F11A ; So    [30] PARENTHESIZED LATIN CAPITAL LETTER A..CIRCLED CD
  #x1F11B ; So    [30] PARENTHESIZED LATIN CAPITAL LETTER A..CIRCLED CD
  #x1F11C ; So    [30] PARENTHESIZED LATIN CAPITAL LETTER A..CIRCLED CD
  #x1F11D ; So    [30] PARENTHESIZED LATIN CAPITAL LETTER A..CIRCLED CD
  #x1F11E ; So    [30] PARENTHESIZED LATIN CAPITAL LETTER A..CIRCLED CD
  #x1F11F ; So    [30] PARENTHESIZED LATIN CAPITAL LETTER A..CIRCLED CD
  #x1F120 ; So    [30] PARENTHESIZED LATIN CAPITAL LETTER A..CIRCLED CD
  #x1F121 ; So    [30] PARENTHESIZED LATIN CAPITAL LETTER A..CIRCLED CD
  #x1F122 ; So    [30] PARENTHESIZED LATIN CAPITAL LETTER A..CIRCLED CD
  #x1F123 ; So    [30] PARENTHESIZED LATIN CAPITAL LETTER A..CIRCLED CD
  #x1F124 ; So    [30] PARENTHESIZED LATIN CAPITAL LETTER A..CIRCLED CD
  #x1F125 ; So    [30] PARENTHESIZED LATIN CAPITAL LETTER A..CIRCLED CD
  #x1F126 ; So    [30] PARENTHESIZED LATIN CAPITAL LETTER A..CIRCLED CD
  #x1F127 ; So    [30] PARENTHESIZED LATIN CAPITAL LETTER A..CIRCLED CD
  #x1F128 ; So    [30] PARENTHESIZED LATIN CAPITAL LETTER A..CIRCLED CD
  #x1F129 ; So    [30] PARENTHESIZED LATIN CAPITAL LETTER A..CIRCLED CD
  #x1F12A ; So    [30] PARENTHESIZED LATIN CAPITAL LETTER A..CIRCLED CD
  #x1F12B ; So    [30] PARENTHESIZED LATIN CAPITAL LETTER A..CIRCLED CD
  #x1F12C ; So    [30] PARENTHESIZED LATIN CAPITAL LETTER A..CIRCLED CD
  #x1F12D ; So    [30] PARENTHESIZED LATIN CAPITAL LETTER A..CIRCLED CD
  #x1F130 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F131 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F132 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F133 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F134 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F135 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F136 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F137 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F138 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F139 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F13A ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F13B ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F13C ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F13D ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F13E ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F13F ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F140 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F141 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F142 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F143 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F144 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F145 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F146 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F147 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F148 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F149 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F14A ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F14B ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F14C ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F14D ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F14E ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F14F ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F150 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F151 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F152 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F153 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F154 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F155 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F156 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F157 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F158 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F159 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F15A ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F15B ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F15C ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F15D ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F15E ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F15F ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F160 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F161 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F162 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F163 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F164 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F165 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F166 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F167 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F168 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F169 ; So    [58] SQUARED LATIN CAPITAL LETTER A..NEGATIVE CIRCLED LATIN CAPITAL LETTER Z
  #x1F170 ; So    [30] NEGATIVE SQUARED LATIN CAPITAL LETTER A..NEGATIVE SQUARED SA
  #x1F171 ; So    [30] NEGATIVE SQUARED LATIN CAPITAL LETTER A..NEGATIVE SQUARED SA
  #x1F172 ; So    [30] NEGATIVE SQUARED LATIN CAPITAL LETTER A..NEGATIVE SQUARED SA
  #x1F173 ; So    [30] NEGATIVE SQUARED LATIN CAPITAL LETTER A..NEGATIVE SQUARED SA
  #x1F174 ; So    [30] NEGATIVE SQUARED LATIN CAPITAL LETTER A..NEGATIVE SQUARED SA
  #x1F175 ; So    [30] NEGATIVE SQUARED LATIN CAPITAL LETTER A..NEGATIVE SQUARED SA
  #x1F176 ; So    [30] NEGATIVE SQUARED LATIN CAPITAL LETTER A..NEGATIVE SQUARED SA
  #x1F177 ; So    [30] NEGATIVE SQUARED LATIN CAPITAL LETTER A..NEGATIVE SQUARED SA
  #x1F178 ; So    [30] NEGATIVE SQUARED LATIN CAPITAL LETTER A..NEGATIVE SQUARED SA
  #x1F179 ; So    [30] NEGATIVE SQUARED LATIN CAPITAL LETTER A..NEGATIVE SQUARED SA
  #x1F17A ; So    [30] NEGATIVE SQUARED LATIN CAPITAL LETTER A..NEGATIVE SQUARED SA
  #x1F17B ; So    [30] NEGATIVE SQUARED LATIN CAPITAL LETTER A..NEGATIVE SQUARED SA
  #x1F17C ; So    [30] NEGATIVE SQUARED LATIN CAPITAL LETTER A..NEGATIVE SQUARED SA
  #x1F17D ; So    [30] NEGATIVE SQUARED LATIN CAPITAL LETTER A..NEGATIVE SQUARED SA
  #x1F17E ; So    [30] NEGATIVE SQUARED LATIN CAPITAL LETTER A..NEGATIVE SQUARED SA
  #x1F17F ; So    [30] NEGATIVE SQUARED LATIN CAPITAL LETTER A..NEGATIVE SQUARED SA
  #x1F180 ; So    [30] NEGATIVE SQUARED LATIN CAPITAL LETTER A..NEGATIVE SQUARED SA
  #x1F181 ; So    [30] NEGATIVE SQUARED LATIN CAPITAL LETTER A..NEGATIVE SQUARED SA
  #x1F182 ; So    [30] NEGATIVE SQUARED LATIN CAPITAL LETTER A..NEGATIVE SQUARED SA
  #x1F183 ; So    [30] NEGATIVE SQUARED LATIN CAPITAL LETTER A..NEGATIVE SQUARED SA
  #x1F184 ; So    [30] NEGATIVE SQUARED LATIN CAPITAL LETTER A..NEGATIVE SQUARED SA
  #x1F185 ; So    [30] NEGATIVE SQUARED LATIN CAPITAL LETTER A..NEGATIVE SQUARED SA
  #x1F186 ; So    [30] NEGATIVE SQUARED LATIN CAPITAL LETTER A..NEGATIVE SQUARED SA
  #x1F187 ; So    [30] NEGATIVE SQUARED LATIN CAPITAL LETTER A..NEGATIVE SQUARED SA
  #x1F188 ; So    [30] NEGATIVE SQUARED LATIN CAPITAL LETTER A..NEGATIVE SQUARED SA
  #x1F189 ; So    [30] NEGATIVE SQUARED LATIN CAPITAL LETTER A..NEGATIVE SQUARED SA
  #x1F18A ; So    [30] NEGATIVE SQUARED LATIN CAPITAL LETTER A..NEGATIVE SQUARED SA
  #x1F18B ; So    [30] NEGATIVE SQUARED LATIN CAPITAL LETTER A..NEGATIVE SQUARED SA
  #x1F18C ; So    [30] NEGATIVE SQUARED LATIN CAPITAL LETTER A..NEGATIVE SQUARED SA
  #x1F18D ; So    [30] NEGATIVE SQUARED LATIN CAPITAL LETTER A..NEGATIVE SQUARED SA
  #x1F18F ; So     [2] NEGATIVE SQUARED WC..SQUARE DJ
  #x1F190 ; So     [2] NEGATIVE SQUARED WC..SQUARE DJ
  #x1F19B ; So    [18] SQUARED THREE D..SQUARED VOD
  #x1F19C ; So    [18] SQUARED THREE D..SQUARED VOD
  #x1F19D ; So    [18] SQUARED THREE D..SQUARED VOD
  #x1F19E ; So    [18] SQUARED THREE D..SQUARED VOD
  #x1F19F ; So    [18] SQUARED THREE D..SQUARED VOD
  #x1F1A0 ; So    [18] SQUARED THREE D..SQUARED VOD
  #x1F1A1 ; So    [18] SQUARED THREE D..SQUARED VOD
  #x1F1A2 ; So    [18] SQUARED THREE D..SQUARED VOD
  #x1F1A3 ; So    [18] SQUARED THREE D..SQUARED VOD
  #x1F1A4 ; So    [18] SQUARED THREE D..SQUARED VOD
  #x1F1A5 ; So    [18] SQUARED THREE D..SQUARED VOD
  #x1F1A6 ; So    [18] SQUARED THREE D..SQUARED VOD
  #x1F1A7 ; So    [18] SQUARED THREE D..SQUARED VOD
  #x1F1A8 ; So    [18] SQUARED THREE D..SQUARED VOD
  #x1F1A9 ; So    [18] SQUARED THREE D..SQUARED VOD
  #x1F1AA ; So    [18] SQUARED THREE D..SQUARED VOD
  #x1F1AB ; So    [18] SQUARED THREE D..SQUARED VOD
  #x1F1AC ; So    [18] SQUARED THREE D..SQUARED VOD
))

(defun eaw-set-width (width)
  (when (= emacs-major-version 22)
    (utf-translate-cjk-set-unicode-range east-asian-ambiguous))
  (when (>= emacs-major-version 23)
    (while (char-table-parent char-width-table)
      (setq char-width-table (char-table-parent char-width-table)))
    (let ((table (make-char-table nil)))
      (mapc (lambda (range) (set-char-table-range table range width))
            east-asian-ambiguous)
      (optimize-char-table table)
      (set-char-table-parent table char-width-table)
      (setq char-width-table table))))

(defun eaw-fullwidth ()
  (eaw-set-width 2))

(defun eaw-halfwidth ()
  (eaw-set-width 1))

(provide 'eaw)

;;; eaw.el ends here
